apiVersion: v1
kind: Service
metadata:
  name: svc-20260610170630
  namespace: enlight-staging
  labels:
    app: svc-20260610170630
spec:
  selector:
    app: svc-20260610170630
  ports:
    - name: http
      port: 80
      targetPort: 8000
