apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enlight-staging

resources:
  - ../../../../workload/fastapi/k8s/base

images:
  - name: PLACEHOLDER_IMAGE
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/enlight-fastapi
    newTag: demo-pass
