apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: enlight-staging
  labels:
    app: nginx-demo
    app.kubernetes.io/part-of: enlight-lab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
        team: enlight-demo
        env: staging
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:1.27-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-site
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: nginx-site
          configMap:
            name: nginx-demo-site
