apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enlight-staging

resources:
  - ../../../../workload/fastapi/k8s/base

images:
  - name: PLACEHOLDER_IMAGE
    newName: bom.ocir.io/bmitpaosivqx/enlight-fastapi
    newTag: demo-pass

patches:
  - target:
      kind: Deployment
      name: fastapi
    patch: |
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 15
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 10
